# Generated by Django 3.1 on 2021-01-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotbit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exch_direction', models.CharField(max_length=20)),
                ('buy', models.FloatField()),
                ('sell', models.FloatField()),
                ('symbol', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(verbose_name='Активный')),
            ],
            options={
                'db_table': 'module_hotbit',
            },
        ),
    ]
