# Generated by Django 3.1 on 2021-01-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotbit_module', '0002_hotbit_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotbit',
            name='exch_direction',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='hotbit',
            name='symbol',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='hotbit',
            name='volume',
            field=models.FloatField(max_length=30),
        ),
    ]
