# Generated by Django 3.1 on 2021-02-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotbit_module', '0004_auto_20210118_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotbit',
            name='tsymbol',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
