# Generated by Django 3.1 on 2021-04-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotbit_module', '0005_hotbit_tsymbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotbit',
            name='buy',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='hotbit',
            name='sell',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='hotbit',
            name='volume',
            field=models.FloatField(blank=True, max_length=30, null=True),
        ),
    ]
