# Generated by Django 3.1 on 2021-04-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotbit_module', '0006_auto_20210403_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotbitMarkets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(max_length=30)),
                ('token', models.CharField(blank=True, max_length=30, null=True)),
                ('tsymbol', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(verbose_name='Активный')),
            ],
            options={
                'db_table': 'hotbit_markets',
            },
        ),
        migrations.AlterField(
            model_name='hotbit',
            name='buy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotbit',
            name='sell',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
