# Generated by Django 3.1 on 2021-04-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotbit_module', '0007_auto_20210406_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotbitmarkets',
            name='market',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='hotbitmarkets',
            name='tsymbol',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
