# Generated by Django 3.1 on 2021-04-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotbit_module', '0008_auto_20210406_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotbitmarkets',
            name='tsymbol',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
