# Generated by Django 3.1 on 2020-08-16 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uniswap_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='uniswap',
            table='module_uniswap',
        ),
    ]
