# Generated by Django 3.1 on 2020-08-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniswap_module', '0003_uniswap_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniswapOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exch_direction', models.CharField(max_length=20)),
                ('highest_bid', models.FloatField()),
                ('lowest_ask', models.FloatField()),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'db_table': 'module_uniswap_one',
            },
        ),
    ]
