# Generated by Django 3.1 on 2020-08-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniswap_module', '0004_uniswapone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniswap',
            name='exch_direction',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='uniswapone',
            name='exch_direction',
            field=models.CharField(max_length=256),
        ),
    ]
