# Generated by Django 3.1 on 2020-09-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniswap_module', '0006_auto_20200827_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniswap',
            name='is_active',
            field=models.BooleanField(verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='uniswapone',
            name='is_active',
            field=models.BooleanField(verbose_name='Активный'),
        ),
    ]
