# Generated by Django 3.1 on 2020-08-16 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bancor_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bancor',
            table='module_bancor',
        ),
    ]
