# Generated by Django 3.1 on 2020-08-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancor_module', '0004_auto_20200824_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bancor',
            name='is_active',
            field=models.BooleanField(verbose_name='Активный'),
        ),
    ]
