# Generated by Django 3.1 on 2021-02-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancor_module', '0005_auto_20200827_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='bancor',
            name='volume',
            field=models.FloatField(default=0),
        ),
    ]
