# Generated by Django 3.1 on 2021-02-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hitbtc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exch_direction', models.CharField(max_length=30)),
                ('buy', models.FloatField()),
                ('sell', models.FloatField()),
                ('symbol', models.CharField(max_length=30)),
                ('tsymbol', models.CharField(blank=True, max_length=100, null=True)),
                ('volume', models.FloatField(max_length=30)),
                ('contract', models.CharField(blank=True, max_length=100, null=True)),
                ('decimals', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(verbose_name='Активный')),
            ],
            options={
                'db_table': 'module_hitbtc',
            },
        ),
    ]
