# Generated by Django 3.1 on 2021-03-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitbtc_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitbtc',
            name='contract',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='hitbtc',
            name='exch_direction',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='hitbtc',
            name='tsymbol',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
