# Generated by Django 3.1 on 2021-03-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitbtc_module', '0002_auto_20210303_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitbtc',
            name='exch_direction',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='hitbtc',
            name='symbol',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
