# Generated by Django 3.1 on 2021-03-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitbtc_module', '0003_auto_20210312_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitbtc',
            name='contract',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
