# Generated by Django 3.1 on 2021-03-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitbtc_module', '0004_auto_20210316_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitbtc',
            name='tsymbol',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
