# Generated by Django 3.1 on 2021-04-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitbtc_module', '0005_auto_20210316_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitbtc',
            name='buy',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='hitbtc',
            name='sell',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='hitbtc',
            name='volume',
            field=models.FloatField(max_length=30, null=True),
        ),
    ]
