# Generated by Django 3.1 on 2020-08-16 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyber_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='kyber',
            table='module_kyber',
        ),
    ]
