# Generated by Django 3.1 on 2021-02-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyber_module', '0004_auto_20200903_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyber',
            name='volume',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
