# Generated by Django 3.1 on 2021-02-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyber_module', '0006_kyber_token_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyber',
            name='tsymbol',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
