# Generated by Django 3.1 on 2020-08-17 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('idex_module', '0003_auto_20200816_1422'),
        ('kyber_module', '0002_auto_20200816_1422'),
        ('bancor_module', '0002_auto_20200816_1422'),
        ('uniswap_module', '0002_auto_20200816_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangePairs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exch_direction', models.CharField(max_length=20)),
                ('bancor_direction', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bancor_module.bancor')),
                ('idex_direction', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='idex_module.idex')),
                ('kyber_direction', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='kyber_module.kyber')),
                ('uniswap_direction', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uniswap_module.uniswap')),
            ],
            options={
                'db_table': 'exchange_pairs',
            },
        ),
    ]
