# Generated by Django 3.1 on 2020-08-17 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_pairs', '0002_auto_20200817_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangepairs',
            options={'verbose_name': 'ExchangePair', 'verbose_name_plural': 'ExchangePairs'},
        ),
    ]
