# Generated by Django 3.1 on 2020-08-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_pairs', '0003_auto_20200817_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSql',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exch_direction', models.CharField(max_length=100)),
                ('idexbid', models.FloatField()),
                ('idexask', models.FloatField()),
                ('bancorbid', models.FloatField()),
                ('bancorask', models.FloatField()),
                ('bancorid', models.CharField(max_length=255)),
                ('kyberbid', models.FloatField()),
                ('kyberask', models.FloatField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeout_refresh_data', models.IntegerField(verbose_name='Интервал обновления данных')),
                ('timeout_notice', models.IntegerField(verbose_name='Интервал показа нотификаций')),
                ('koef_top', models.IntegerField(verbose_name='Коэффициет топ %')),
                ('koef_low', models.IntegerField(verbose_name='Коэффициет минимума %')),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
                'db_table': 'settings',
            },
        ),
    ]
