# Generated by Django 3.1 on 2020-08-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_pairs', '0004_customsql_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='koef_low',
            field=models.FloatField(verbose_name='Коэффициет минимума %'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='koef_top',
            field=models.FloatField(verbose_name='Коэффициет топ %'),
        ),
    ]
