# Generated by Django 3.1 on 2020-08-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_pairs', '0005_auto_20200823_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='koef_push',
            field=models.FloatField(default=1, help_text='для пуш уведомлений', verbose_name='Коэффициет в % '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='settings',
            name='koef_low',
            field=models.FloatField(help_text='зеленая строка', verbose_name='Коэффициет минимума %'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='koef_top',
            field=models.FloatField(help_text='красная строка', verbose_name='Коэффициет топ %'),
        ),
    ]
