# Generated by Django 3.1 on 2020-09-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_pairs', '0007_exchangepairs_uniswap_one_direction'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustedPairs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(max_length=20)),
                ('contract', models.CharField(max_length=100)),
                ('decimals', models.IntegerField()),
                ('is_active', models.BooleanField(verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Trusted pair',
                'verbose_name_plural': 'Trusted pairs',
                'db_table': 'trusted_pairs',
            },
        ),
        migrations.AlterModelOptions(
            name='exchangepairs',
            options={'verbose_name': 'Exchange pair', 'verbose_name_plural': 'Exchange pairs'},
        ),
    ]
