# Generated by Django 3.1 on 2020-09-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_pairs', '0008_auto_20200903_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparePairs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(max_length=20)),
                ('contract', models.CharField(max_length=100)),
                ('decimals', models.IntegerField()),
                ('is_active', models.BooleanField(verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Compare pair',
                'verbose_name_plural': 'Compare pairs',
                'db_table': 'compare_pairs',
            },
        ),
    ]
