# Generated by Django 3.1 on 2020-09-03 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_pairs', '0009_comparepairs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comparepairs',
            old_name='pair',
            new_name='token',
        ),
        migrations.RenameField(
            model_name='trustedpairs',
            old_name='pair',
            new_name='token',
        ),
    ]
