# Generated by Django 3.1 on 2020-09-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_pairs', '0010_auto_20200903_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trustedpairs',
            name='decimals',
            field=models.IntegerField(null=True),
        ),
    ]
