# Generated by Django 3.1 on 2020-10-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_pairs', '0015_settings_api_keys'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsocketLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('log', models.TextField(verbose_name='Лог')),
            ],
            options={
                'verbose_name': 'Логи вебсокета',
                'verbose_name_plural': 'Лог вебсокета',
                'db_table': 'websocket_log',
            },
        ),
    ]
