# Generated by Django 3.1 on 2021-01-18 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotbit_module', '0004_auto_20210118_1455'),
        ('exchange_pairs', '0016_websocketlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangepairs',
            name='hotbit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hotbit_module.hotbit'),
        ),
    ]
