# Generated by Django 3.1 on 2021-01-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_pairs', '0017_exchangepairs_hotbit'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='market_koef',
            field=models.FloatField(blank=True, help_text='учет отклонения для сравнения бирж в %', null=True, verbose_name='Коэффициет бирж'),
        ),
        migrations.AddField(
            model_name='settings',
            name='market_percent',
            field=models.FloatField(blank=True, help_text='для сравнения бирж в %', null=True, verbose_name='Процент бирж'),
        ),
    ]
