# Generated by Django 3.1 on 2021-02-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_pairs', '0019_profitexchanges'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='currency',
            field=models.FloatField(blank=True, help_text='Курс ETH к BTC', null=True, verbose_name='ETH/BTC'),
        ),
    ]
