# Generated by Django 3.1 on 2021-02-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_pairs', '0020_settings_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparepairs',
            name='tsymbol',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trustedpairs',
            name='tsymbol',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
