# Generated by Django 3.1 on 2021-03-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_pairs', '0021_auto_20210220_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='profitexchanges',
            name='buy_ask',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profitexchanges',
            name='sell_bid',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
