# Generated by Django 3.1 on 2021-03-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_pairs', '0022_auto_20210306_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='profitexchanges',
            name='gas_fast',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profitexchanges',
            name='gas_normal',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
