# Generated by Django 3.1 on 2021-03-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_pairs', '0024_auto_20210311_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='websocketlog',
            name='buy_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='websocketlog',
            name='sell_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
