# Generated by Django 3.1 on 2021-03-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_pairs', '0025_auto_20210312_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='websocketlog',
            name='percent',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='websocketlog',
            name='site',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='websocketlog',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='websocketlog',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
