# Generated by Django 3.1 on 2021-03-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_pairs', '0026_auto_20210312_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='profitexchanges',
            name='sell_symbol',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
