# Generated by Django 3.1 on 2021-03-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_pairs', '0027_profitexchanges_sell_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='trustedpairs',
            name='token_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='websocketlog',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='websocketlog',
            name='sprice',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
