# Generated by Django 3.1 on 2021-04-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_pairs', '0028_auto_20210316_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='currencyUSD',
            field=models.FloatField(blank=True, help_text='Курс ETH к BTC', null=True, verbose_name='ETH/USD'),
        ),
    ]
