# Generated by Django 3.1 on 2021-04-03 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_pairs', '0029_settings_currencyusd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='currencyUSD',
            new_name='currency_usd',
        ),
    ]
