# Generated by Django 3.1 on 2021-04-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_pairs', '0030_auto_20210403_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='currency_usd',
            field=models.FloatField(blank=True, help_text='Курс ETH к USD', null=True, verbose_name='ETH/USD'),
        ),
    ]
