# Generated by Django 3.1 on 2021-04-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_pairs', '0031_auto_20210406_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profitexchanges',
            name='buy',
            field=models.FloatField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profitexchanges',
            name='buy_ask',
            field=models.FloatField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profitexchanges',
            name='percent',
            field=models.FloatField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profitexchanges',
            name='sell',
            field=models.FloatField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profitexchanges',
            name='sell_bid',
            field=models.FloatField(max_length=100),
        ),
    ]
