# Generated by Django 3.1 on 2020-08-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idex_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idex',
            name='highest_bid',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='idex',
            name='lowest_ask',
            field=models.FloatField(),
        ),
    ]
