# Generated by Django 3.1 on 2020-08-16 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idex_module', '0002_auto_20200811_1322'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='idex',
            table='module_idex',
        ),
    ]
