# Generated by Django 3.1 on 2020-08-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idex_module', '0003_auto_20200816_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='idex',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
    ]
