# Generated by Django 3.1 on 2020-09-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idex_module', '0004_idex_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idex',
            name='is_active',
            field=models.BooleanField(verbose_name='Активный'),
        ),
    ]
