# Generated by Django 3.1 on 2021-02-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idex_module', '0005_auto_20200903_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='idex',
            name='token_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='idex',
            name='volume',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
