# Generated by Django 3.1 on 2021-03-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idex_module', '0007_idex_tsymbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdexSocketLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'idex_socket_log',
            },
        ),
    ]
