# Generated by Django 3.1 on 2021-03-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idex_module', '0008_idexsocketlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='idexsocketlog',
            name='log',
            field=models.TextField(blank=True, null=True),
        ),
    ]
