# Generated by Django 3.1 on 2020-08-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exch_direction', models.CharField(max_length=20)),
                ('lowest_ask', models.IntegerField()),
                ('highest_bid', models.IntegerField()),
            ],
        ),
    ]
